### ISSUE TITLE
feature enhance

### ISSUE THREAD

**Issue by kaybinwong** [kernsuite-debian/sharedarray#5]
1、add read/write option when attach
2、what i get should be i created.
```
import numpy as np
import SharedArray as sa

dt = np.dtype([('name', np.int32), ('grades', np.float64)])
a = sa.create("file:///data/test", 2, dt)
a[0] = np.array([(1, 1.0)], dtype=dt)
print(a)
````

when i create file as dtype = dt, but i got byte, 
```
[b'\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F'
 b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']
```
so i must use `np.frombuffer` to serialize data back， it seems not to be nice for user.

**Comment by Athanaseus** [comment]
Hi @kaybinwong, thanks for the issue. 
This must be elevated to the upstream repository [sharedarray](https://gitlab.com/tenzing/shared-array).
NB: Might relate to https://gitlab.com/tenzing/shared-array/-/issues/15.

**Comment by kaybinwong** [comment]
got it, ths
